version: '3.8'

services:
  mysql:
    container_name: playGround_local
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=playGround
      - MYSQL_USER=local_user
      - MYSQL_PASSWORD=LOCAL_TEST
      - MYSQL_ROOT_PASSWORD=LOCAL_TEST
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_ground
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka_ground
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock