spring:
  application:
    name: playground
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/playground?useSSL=false
    username: root
    password: LOCAL_TEST
    driver-class-name: com.mysql.cj.jdbc.Driver

